"""add_system_policies_and_agreements

Revision ID: 0fb18df9aadd
Revises: d3833ed958d0
Create Date: 2026-08-22 17:41:51.561621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fb18df9aadd'
down_revision: Union[str, Sequence[str], None] = 'd3833ed958d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_type', 'version', name='_policy_type_version_uc')
    )
    op.create_table('user_policy_agreements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['system_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Seed the 11 policies
    import uuid
    from datetime import datetime, timezone
    current_time = datetime.now(timezone.utc)

    policy_ids = {k: str(uuid.uuid4()) for k in [
        "terms_and_conditions", "tax_services_use", "disclaimer", "cybersecurity",
        "service_quality", "code_of_conduct", "sla", "records_retention",
        "ai_assistant_disclosure", "data_subject_rights", "privacy_policy"
    ]}

    system_policies_table = sa.table(
        'system_policies',
        sa.column('id', sa.UUID),
        sa.column('title', sa.String),
        sa.column('policy_type', sa.String),
        sa.column('version', sa.String),
        sa.column('content', sa.Text),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime)
    )

    op.bulk_insert(
        system_policies_table,
        [
            {
                "id": policy_ids["terms_and_conditions"],
                "title": "شروط وأحكام استخدام منصة ديوان",
                "policy_type": "terms_and_conditions",
                "version": "1.0",
                "content": "الإطار التعاقدي الذي ينظّم استخدام المنصة وخدماتها.\n\nنطاق الاستخدام:\n- تُستخدم منصة ديوان لأغراض مهنية مرتبطة بالمعلومات والاستشارات الضريبية والمحاسبية داخل المملكة الأردنية الهاشمية.\n- يلتزم المستخدم بتقديم بيانات صحيحة ومحدَّثة، ويتحمّل مسؤولية أي بيانات مضلِّلة أو منتحلة.\n\nالحساب والصلاحيات:\n- حساب المستخدم شخصي وغير قابل للمشاركة، ويتحمّل صاحبه مسؤولية جميع العمليات التي تتم من خلاله.\n- يحق للمنصة تعليق أو إنهاء أي حساب يخالف الشروط أو يحاول تجاوز صلاحيات الوصول.\n\nالمقابل المالي:\n- تُعرض أسعار الاشتراكات والجلسات بشكل واضح قبل الدفع، ولا تُحصَّل أي مبالغ دون موافقة صريحة.\n- تخضع المبالغ المدفوعة لسياسة الاسترداد المعلنة داخل المنصة.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["tax_services_use"],
                "title": "سياسة استخدام الخدمات الضريبية",
                "policy_type": "tax_services_use",
                "version": "1.0",
                "content": "ضوابط استخدام الخدمات والمحتوى الضريبي.\n\nالاستخدام المسموح:\n- استخدام المحتوى الضريبي لأغراض داخلية ومهنية، دون إعادة نشره أو بيعه أو إعادة تقديمه كخدمة.\n- عدم استخدام الخدمة في أي نشاط يهدف للتهرب الضريبي أو الالتفاف على التشريعات.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["disclaimer"],
                "title": "سياسة إخلاء المسؤولية",
                "policy_type": "disclaimer",
                "version": "1.0",
                "content": "حدود مسؤولية المنصة عن المحتوى والمخرجات.\n\nحدود المسؤولية:\n- المعلومات والمحتوى التحليلي داخل المنصة لأغراض إرشادية ولا تغني عن الاستشارة المهنية المباشرة.\n- لا تتحمل المنصة مسؤولية قرارات تتخذ اعتماداً على المخرجات دون مراجعة مستشار معتمد.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["cybersecurity"],
                "title": "سياسة الأمن السيبراني",
                "policy_type": "cybersecurity",
                "version": "1.0",
                "content": "ضوابط حماية الحسابات والأنظمة.\n\nالضوابط:\n- تشفير البيانات أثناء النقل والتخزين، وتقييد الوصول وفق مبدأ الحد الأدنى من الصلاحيات.\n- مراقبة محاولات الدخول غير المصرح بها والاستجابة للحوادث وفق إجراءات معتمدة.\n\nمسؤولية المستخدم:\n- استخدام كلمة مرور قوية وعدم مشاركة بيانات الدخول أو رموز التحقق مع أي طرف.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["service_quality"],
                "title": "ميثاق جودة الخدمات",
                "policy_type": "service_quality",
                "version": "1.0",
                "content": "معايير الجودة الملزمة لمقدمي الخدمة على المنصة.\n\nمعايير الجودة:\n- الالتزام بالمواعيد المحجوزة وإشعار الطرف الآخر مسبقاً عند التعذر.\n- توثيق ملخص كل جلسة والمرفقات والفواتير داخل غرفة الاستشارة.\n- الحفاظ على تقييم لا يقل عن 4.0 من 5 وفق تقييمات المستفيدين.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["code_of_conduct"],
                "title": "مدونة السلوك المهني والأخلاقي",
                "policy_type": "code_of_conduct",
                "version": "1.0",
                "content": "قواعد السلوك المتوقعة من المستشارين والمستخدمين.\n\nالمبادئ:\n- النزاهة والحياد وعدم تضارب المصالح، والإفصاح عنه فور نشوئه.\n- احترام السرية المهنية وعدم إفشاء معلومات العملاء.\n- عدم تقديم وعود بنتائج مضمونة أو تفسيرات مخالفة للتشريعات النافذة.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["sla"],
                "title": "سياسة مستوى الخدمة",
                "policy_type": "sla",
                "version": "1.0",
                "content": "التزامات التوافر وأزمنة الاستجابة.\n\nالتوافر:\n- تسعى المنصة لتوافر تشغيلي لا يقل عن 99% شهرياً باستثناء الصيانة المجدولة المعلنة مسبقاً.\n\nأزمنة الاستجابة:\n- الاستجابة لطلبات الدعم الحرجة خلال 4 ساعات عمل، والطلبات العادية خلال يوم عمل واحد.\n- مراجعة طلبات اعتماد المستشارين خلال 4 أيام عمل.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["records_retention"],
                "title": "سياسة الاحتفاظ بالسجلات والمستندات",
                "policy_type": "records_retention",
                "version": "1.0",
                "content": "مدد الاحتفاظ بالسجلات وآلية الإتلاف الآمن.\n\nمدد الاحتفاظ:\n- تُحفظ سجلات الاستشارات والفواتير للمدة التي تفرضها التشريعات الضريبية والمحاسبية النافذة.\n- تُحفظ سجلات الدخول والتدقيق الأمني لمدة كافية لأغراض التحقيق في الحوادث.\n\nالإتلاف:\n- تُتلف السجلات بشكل آمن وغير قابل للاسترجاع عند انتهاء مدة الاحتفاظ.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["ai_assistant_disclosure"],
                "title": "الإفصاح الخاص بمساعد ديوان الذكي",
                "policy_type": "ai_assistant_disclosure",
                "version": "1.0",
                "content": "حدود مخرجات الذكاء الاصطناعي ودور المراجعة البشرية.\n\nطبيعة المخرجات:\n- مخرجات المساعد الذكي إرشادية وتستند إلى مصادر تشريعية مفهرسة داخل المنصة مع الإشارة إلى المصدر.\n- لا تُعد هذه المخرجات رأياً قانونياً نهائياً إلا بعد مراجعة مستشار معتمد.\n\nالبيانات والتدريب:\n- لا تُستخدم بيانات المستخدمين أو محتوى الاستشارات لتدريب نماذج أطراف ثالثة.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["data_subject_rights"],
                "title": "سياسة حقوق أصحاب البيانات الشخصية",
                "policy_type": "data_subject_rights",
                "version": "1.0",
                "content": "حقوقك في الوصول والتصحيح والحذف والاعتراض.\n\nحقوقك:\n- الوصول إلى بياناتك الشخصية ومعرفة أوجه استخدامها.\n- تصحيح البيانات غير الدقيقة أو تحديثها من إعدادات الحساب.\n- طلب حذف البيانات بما لا يتعارض مع الالتزامات القانونية أو النزاعات القائمة.\n- الاعتراض على معالجة معينة أو سحب الموافقة مستقبلاً.\n\nآلية الطلب:\n- تُقدّم الطلبات عبر support@diwanjo.com ويُرد عليها خلال مدة معقولة لا تتجاوز ثلاثين يوماً.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            },
            {
                "id": policy_ids["privacy_policy"],
                "title": "سياسة الخصوصية وحماية البيانات الشخصية",
                "policy_type": "privacy_policy",
                "version": "1.0",
                "content": "كيف نجمع بياناتك ونعالجها ونحميها.\n\nالبيانات التي نجمعها:\n- بيانات الحساب الأساسية، بيانات الملف الضريبي، المستندات التي ترفعها، وسجلات الاستخدام اللازمة لأمن المنصة.\n\nأساس المعالجة:\n- تُعالج البيانات لتنفيذ الخدمة المتفق عليها، وللامتثال للالتزامات القانونية، ولحماية المنصة من إساءة الاستخدام.\n- لا تُباع البيانات الشخصية ولا تُشارك مع أطراف غير مخولة.\n\nالحماية:\n- تُطبّق ضوابط تشفير ووصول قائمة على الدور، ويُقيّد الوصول للمستندات بأصحابها والمخولين فقط.",
                "is_active": True,
                "created_at": current_time,
                "updated_at": current_time
            }
        ]
    )

    # Migrate existing users' privacy policy agreement to user_policy_agreements
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            f"INSERT INTO user_policy_agreements (id, user_id, policy_id, accepted_at) "
            f"SELECT gen_random_uuid(), id, '{policy_ids['privacy_policy']}', now() "
            f"FROM users WHERE accepted_policy_version_id IS NOT NULL"
        )

    op.drop_constraint('fk_users_privacy_policy', 'users', type_='foreignkey')
    op.drop_column('users', 'accepted_policy_version_id')
    op.drop_table('privacy_policies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_policy_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table('privacy_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='privacy_policies_pkey'),
    sa.UniqueConstraint('version', name='privacy_policies_version_key')
    )
    op.create_foreign_key('fk_users_privacy_policy', 'users', 'privacy_policies', ['accepted_policy_version_id'], ['id'])
    op.drop_table('user_policy_agreements')
    op.drop_table('system_policies')
    # ### end Alembic commands ###
