"""add specific_date to consultant_availabilities

Revision ID: 8e7adc387186
Revises: 1e1bde39e7bb
Create Date: 2026-09-13 13:58:29.936610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e7adc387186'
down_revision: Union[str, Sequence[str], None] = '1e1bde39e7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_status'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_trigger_event'), table_name='automation_rules')
    op.add_column('consultant_availabilities', sa.Column('specific_date', sa.Date(), nullable=True))
    op.alter_column('recurring_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('recurring_invoices_user_id_fkey'), 'recurring_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_invoices', 'users', ['user_id'], ['id'])
    op.alter_column('refunded_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('refunded_invoices_user_id_fkey'), 'refunded_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'refunded_invoices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refunded_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('refunded_invoices_user_id_fkey'), 'refunded_invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refunded_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'recurring_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('recurring_invoices_user_id_fkey'), 'recurring_invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recurring_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('consultant_availabilities', 'specific_date')
    op.create_index(op.f('ix_automation_rules_trigger_event'), 'automation_rules', ['trigger_event'], unique=False)
    op.create_index(op.f('ix_automation_rules_status'), 'automation_rules', ['status'], unique=False)
    # ### end Alembic commands ###
