"""support_quick_consultations

Revision ID: 9a3d2449cff1
Revises: cd5ff4ae5f84
Create Date: 2026-08-29 15:18:19.053612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3d2449cff1'
down_revision: Union[str, Sequence[str], None] = 'cd5ff4ae5f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    session_type_enum = postgresql.ENUM('audio_call', 'video_call', 'chat', name='session_type')
    session_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('appointments', sa.Column('session_type', postgresql.ENUM('audio_call', 'video_call', 'chat', name='session_type', inherit_schema=True), nullable=True))
    op.add_column('consultant_availabilities', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('consultant_profiles', sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultant_profiles', 'price_per_hour')
    op.drop_column('consultant_availabilities', 'end_time')
    op.drop_column('appointments', 'session_type')

    session_type_enum = postgresql.ENUM('audio_call', 'video_call', 'chat', name='session_type')
    session_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
