"""add_registration_fields_privacy_and_approval

Revision ID: d3833ed958d0
Revises: 
Create Date: 2026-08-22 17:24:50.359425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3833ed958d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create legal_form enum type in postgres
    legal_form_enum = postgresql.ENUM(
        'individual', 'sole_proprietorship', 'llc', 'private_joint_stock',
        'public_joint_stock', 'general_partnership', 'limited_partnership',
        'independent_entity', 'researcher', 'association', 'non_profit',
        name='legal_form'
    )
    legal_form_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('privacy_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.add_column('appointments', sa.Column('google_event_id', sa.String(length=200), nullable=True))
    op.add_column('consultant_profiles', sa.Column('activity_type', sa.String(length=100), nullable=True))
    op.add_column('consultant_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('consultant_profiles', sa.Column('certificates_licenses', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('legal_form', postgresql.ENUM('individual', 'sole_proprietorship', 'llc', 'private_joint_stock', 'public_joint_stock', 'general_partnership', 'limited_partnership', 'independent_entity', 'researcher', 'association', 'non_profit', name='legal_form', inherit_schema=True), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('url_slug', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('commercial_register_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('verification_status', postgresql.ENUM('pending', 'approved', 'rejected', name='verification_status', inherit_schema=True), nullable=False, server_default='approved'))
    op.add_column('users', sa.Column('accepted_policy_version_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'entity_type',
               existing_type=postgresql.ENUM('individual', 'company', 'researcher', name='entity_type'),
               nullable=False,
               existing_server_default=sa.text("'individual'::entity_type"))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_unique_constraint('users_url_slug_key', 'users', ['url_slug'])
    op.create_foreign_key('fk_users_privacy_policy', 'users', 'privacy_policies', ['accepted_policy_version_id'], ['id'])

    # Seed default privacy policy version 1.0
    import uuid
    policy_id = str(uuid.uuid4())
    op.execute(
        sa.text(
            "INSERT INTO privacy_policies (id, version, content, is_active, created_at, updated_at) "
            f"VALUES ('{policy_id}', '1.0', "
            "'سياسة الخصوصية الافتراضية لمنصة الاستشارات. باستخدامك للمنصة، فإنك توافق على جمع واستخدام بياناتك وفقاً لهذه السياسة.', "
            "true, now(), now())"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_privacy_policy', 'users', type_='foreignkey')
    op.drop_constraint('users_url_slug_key', 'users', type_='unique')
    op.alter_column('users', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'appointment_reminders',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'ar'::character varying"))
    op.alter_column('users', 'entity_type',
               existing_type=postgresql.ENUM('individual', 'company', 'researcher', name='entity_type'),
               nullable=True,
               existing_server_default=sa.text("'individual'::entity_type"))
    op.drop_column('users', 'accepted_policy_version_id')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'address')
    op.drop_column('users', 'title')
    op.drop_column('users', 'commercial_register_url')
    op.drop_column('users', 'url_slug')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'legal_form')
    op.drop_column('consultant_profiles', 'certificates_licenses')
    op.drop_column('consultant_profiles', 'years_of_experience')
    op.drop_column('consultant_profiles', 'activity_type')
    op.drop_column('appointments', 'google_event_id')
    op.drop_table('privacy_policies')

    # Drop legal_form enum type
    legal_form_enum = postgresql.ENUM(
        'individual', 'sole_proprietorship', 'llc', 'private_joint_stock',
        'public_joint_stock', 'general_partnership', 'limited_partnership',
        'independent_entity', 'researcher', 'association', 'non_profit',
        name='legal_form'
    )
    legal_form_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
