"""add_cover_image_url_to_consultant_profiles

Revision ID: f3bfa4b1edd3
Revises: 8e7adc387186
Create Date: 2026-09-16 19:13:14.900093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bfa4b1edd3'
down_revision: Union[str, Sequence[str], None] = '8e7adc387186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('automation_rules_created_by_fkey', 'automation_rules', type_='foreignkey')
    op.create_foreign_key(None, 'automation_rules', 'users', ['created_by'], ['id'])
    op.add_column('consultant_profiles', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultant_profiles', 'cover_image_url')
    op.drop_constraint(None, 'automation_rules', type_='foreignkey')
    op.create_foreign_key('automation_rules_created_by_fkey', 'automation_rules', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
